[package]
name = "valid8_derive"
version = "0.1.2"
edition = "2021"
repository = "https://github.com/JacoMalan1/valid8"
license = "Apache-2.0"
description = "Derive macros for valid8"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.92"
quote = "1.0.38"
syn = "2.0.92"
